### ISSUE TITLE
avoid adjustment of import statement

### ISSUE THREAD

**Issue by dornech** [maresb/hatch-vcs-footgun-example#2]
to make workaround more copy&paste

ist it possible to replace:
` from hatch_vcs_footgun_example._version import __version__  # noqa: F401`

with some generic code ?

something like 
```
from importlib import import_module
versionmodule = import_module(__package__ + "._version")
__version__ = getattr(versionmodule, "__version__")

```

**Comment by maresb** [comment]
Hey, thanks for the feedback!

Would a relative import work and achieve the same effect?

```python
from ._version import __version__  # noqa: F401
```

**Comment by dornech** [comment]
upps, was too easy for me.
Sometimes you miss the forest for the trees
